---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Networking:
    - OPNsense:
        href: https://opnsense.cedoromal.com/
        icon: opnsense
        description: an open source, FreeBSD-based firewall and routing software developed by Deciso
        ping: opnsense.cedoromal.com