---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: CEDoromal Homepage

description: My selfhosted Homepage

color: stone

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom

showStats: true

statusStyle: "dot"

layout:
  Networking:
    icon: mdi-network-outline
  Miscellaneous:
    icon: mdi-dots-grid
  Bots:
    icon: mdi-robot-outline
  Auth:
    icon: mdi-lock-outline